### create user

POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "1231321"
}

### sign in for user

POST http://localhost:4000/auth/signin
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "1231321"
}

### sign out

POST http://localhost:4000/auth/signout
Content-Type: application/json

{

}


### get current user

GET http://localhost:4000/auth/whoami



### find all user by email

GET http://localhost:4000/auth?email=abc@gmail.com



### find User

GET http://localhost:4000/auth/2


### delete user by id

DELETE http://localhost:4000/auth/11


### update user by id

PATCH http://localhost:4000/auth/5
Content-Type: application/json

{
  "email": "abc@gmail.com",
  "password": "12313213333333333"
}
