### List all tickets
GET http://localhost:3000/tickets

### Get single ticket
GET http://localhost:3000/tickets/3159

### create new tickets
POST http://localhost:3000/tickets
Content-Type: application/json

{
  "content": "Hello tickets"
}